### PR TITLE
Ver 2 lesson11: different way to get kutta cond.

### PR DESCRIPTION
**Pull request by ncclementi**
Adding a version 2 of lesson 11 where we implemented
a different way to get the kutta condition. This way
is based on the math exercise from lesson11.

If we think this version is better we can remove the previous
one.

### CODE REVIEW

**Comment by mesnardo** [comment]
@ncclementi , I really like your idea of rewriting the Kutta condition.

I also made some modifications to the code so that, we only compute the integral over the panels twice (one for the source matrix, one for the vortex matrix).

I wrote again the docstrings to add the type of the parameters.

The text still has to be checked (I found some typo).

**Comment by ncclementi** [comment]
I agree with all of the changes, expect I'm not sure if we should replace u_inf by speed in the freestream class. In the previous lessons we were using u_inf.  Then, we can leave it as u_inf in lesson 11 or we can change it in the previous ones. I'm not sure what it's better in terms of readability. 

About the text I read it again, I fix some typo, but most of the content is from the original lesson, so it should be ok.

**Comment by mesnardo** [comment]
Going back to the previous notation for the freestream speed.

Modifying the text about the Kutta-condition.

**Comment by gforsyth** [comment]
Ping @mesnardo @ncclementi 
I just updated Naty's better kutta condition notebook to Python 3 and updated the notebook.  Can you guys take a look at it and do a sanity check so we can merge this thing in?

**Comment by mesnardo** [comment]
@gil : I guess when you changed the notebook version, it became difficult to see the differences with `git diff`. So, just reading through the notebook, I am ok with your modifications.

**Comment by ncclementi** [comment]
@gforsyth : I read the notebook and it looks fine to me. The only thing it's in the kutta condition function, the way I wrote the comments that explain why we do it that way, maybe are not that nice; but it's a minor detail.

**Comment by gforsyth** [comment]
Ok, I'm merging this.  if we want to rework the comments that can be opened in a separate PR.

**Pull request merged**
