### PR TITLE
AirfoilCharacteristics

### PR DESCRIPTION
**Pull request by amiya89**

### CODE REVIEW

**Comment by labarba** [comment]
You need to do the pull request to the right repository!
https://github.com/barbagroup/AeroPython-studentprojects

**Comment by amiya89** [comment]
I’m having trouble cloning the project repository. I have created a student project folder in the aeropython repository. Is it alright if I just push that?


Amiya Chowdhury






Sent from Windows Mail





From: Lorena A. Barba
Sent: ‎Wednesday‎, ‎May‎ ‎13‎, ‎2015 ‎10‎:‎00‎ ‎PM
To: barbagroup/AeroPython
Cc: amiya89





You need to do the pull request to the right repository!
https://github.com/barbagroup/AeroPython-studentprojects

**Comment by labarba** [comment]
No, because if you push to the AeroPython repository, all your changes to the course lessons will be included with that pull request.

Come by our office and we'll help you if you still have trouble with GitHub.
_______________________________________
Lorena A. Barba
Associate Professor of Mechanical and Aerospace Engineering
The George Washington University
http://twitter.com/LorenaABarba

**Comment by amiya89** [comment]
It isn’t possible for me to come in today. I can come in tomorrow if that’s alright. Should I send  you a link to my notebook at least?


Amiya Chowdhury






Sent from Windows Mail





From: Lorena A. Barba
Sent: ‎Thursday‎, ‎May‎ ‎14‎, ‎2015 ‎8‎:‎22‎ ‎AM
To: barbagroup/AeroPython
Cc: amiya89




No, because if you push to the AeroPython repository, all your changes to the course lessons will be included with that pull request.

Come by our office and we'll help you if you still have trouble with GitHub.
_______________________________________
Lorena A. Barba
Associate Professor of Mechanical and Aerospace Engineering
The George Washington University
http://twitter.com/LorenaABarba

**Comment by amiya89** [comment]
I am having trouble pushing my files into the correct repository. I forked the project repository and then cloned it to my laptop. I put my folder inside and then committed it. When I tried to publish it after that, it failed. I tried to clone it from my browser as well, but I received an error message saying I was missing some .dll file.


I am out of town today but I will be coming in tomorrow. I have attached my report and most of the relevant files in a zip to this email.


Amiya Chowdhury






Sent from Windows Mail





From: Lorena A. Barba
Sent: ‎Thursday‎, ‎May‎ ‎14‎, ‎2015 ‎8‎:‎22‎ ‎AM
To: barbagroup/AeroPython
Cc: amiya89




No, because if you push to the AeroPython repository, all your changes to the course lessons will be included with that pull request.

Come by our office and we'll help you if you still have trouble with GitHub.
_______________________________________
Lorena A. Barba
Associate Professor of Mechanical and Aerospace Engineering
The George Washington University
http://twitter.com/LorenaABarba

**Pull request closed without merging**
